version: '3.8'

volumes:
  database-backup:
  shared-backup:

  users-database:
  content-database:

services:
  controller:
    image: alexbidenko/docker-postgres-backuper:17postgres
    volumes:
      - database-backup:/var/lib/postgresql/backup/data
      - shared-backup:/var/lib/postgresql/backup/shared

      - users-database:/var/lib/postgresql/databases/users
      - company-database:/var/lib/postgresql/databases/company
    environment:
      MODE: production
      SERVER: production
      COPING_TO_SHARED: true
      BACKUP_TARGET: "local,s3"
      DATABASE_LIST: "users,content"
      TZ: Europe/London
      USERS_POSTGRES_USER: postgres
      USERS_POSTGRES_PASSWORD: postgres
      USERS_POSTGRES_DB: postgres
      USERS_POSTGRES_HOST: users-database
      CONTENT_POSTGRES_USER: postgres
      CONTENT_POSTGRES_PASSWORD: postgres
      CONTENT_POSTGRES_DB: postgres
      CONTENT_POSTGRES_HOST: content-database
      S3_BUCKET: my-backups
      S3_PREFIX: project-a/prod
      S3_REGION: eu-central-1
      S3_ENDPOINT: https://s3.eu-central-1.amazonaws.com
      S3_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_USE_TLS: "true"
      S3_FORCE_PATH_STYLE: "false"
      S3_STORAGE_CLASS: STANDARD
      S3_MAX_RETRIES: "3"
    user: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  users-database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - users-database:/var/lib/postgresql/data
    user: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  content-database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - content-database:/var/lib/postgresql/data
    user: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
