on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Build and publish application

    strategy:
      matrix:
        postgres: ['14', '15', '16', '17']

    runs-on: ubuntu-24.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Get version
        run: |
          echo "CURRENT_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/postgres-backuper:${GITHUB_REF#refs/*/v}-${{ matrix.postgres }}postgres" >> $GITHUB_ENV
          echo "POSTGRES_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/postgres-backuper:${{ matrix.postgres }}postgres" >> $GITHUB_ENV
          echo "LATEST_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/postgres-backuper:latest" >> $GITHUB_ENV

      - name: Prepare tags
        id: prepare-tags
        run: |
          if [[ ${{ matrix.postgres }} == '17' ]]; then
            echo "tags=${{ env.CURRENT_TAG }},${{ env.POSTGRES_TAG }},${{ env.LATEST_TAG }}" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ env.CURRENT_TAG }},${{ env.POSTGRES_TAG }}" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.prepare-tags.outputs.tags }}
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ env.CURRENT_TAG }}
          dockerfile: ./Dockerfile
          annotations: true
