on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Build and publish application

    strategy:
      matrix:
        postgres: ['14', '15', '16']

    runs-on: ubuntu-22.04

    env:
      TAGS: ${{ matrix.postgres == '16' && '${{ secrets.DOCKER_HUB_USERNAME }}/docker-postgres-backuper:latest,' || '' }}${{ secrets.DOCKER_HUB_USERNAME }}/docker-postgres-backuper:${{ matrix.postgres }}-${{ env.RELEASE_VERSION }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.TAGS }}
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-postgres-backuper:${{ env.RELEASE_VERSION }}
          dockerfile: ./Dockerfile
          annotations: true
